Второй модуль
js-tasks-ru/jsbasic-20220113_kernelidze pull request #3
Opened 2022-01-25 11:58 UTC by kernelidze

В первом задании не очень нравится, как выполнил сравнение в if. Возможно есть более изящный и краткий способ?

2022-01-25 11:59 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-26 11:00 UTC, SinimaWath requested changes

2022-01-26 11:00 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    if (!isNaN(value[key]) && value[key] !== false && value[key] !== true && value[key] !== Infinity && value[key] !== -Infinity) {
Можно сократить до:

`if (typeof value[key] === 'number' && isFinite(value[key]))`

2022-01-26 14:21 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-28 13:40 UTC, SinimaWath approved these changes
все ок

2022-01-28 13:41 UTC, merged